### ISSUE TITLE
typo for ElectrOS for mac ARM .dmg

### ISSUE THREAD

**Issue by MMogna** [Elemento-Modular-Cloud/elemento-gui-1.0.5#21]
Double capital "E" typo for Electros mac ARM .dmg release
![Screenshot 2024-10-02 at 16 06 07](https://github.com/user-attachments/assets/0e35de3d-5d51-43c5-876c-c843671c432f)

**Comment by fvalle1** [comment]
@filippo-ferrando may you look into this, please?

**Comment by filippo-ferrando** [comment]
issue solved on develop branch, not effective until merged on main
